# Validator controller for IngressClass: nginx (default)
controller:
  image:
    repository: ingress-nginx-validator
    tag: v1.14.3-patched
    digest: ""

  admissionWebhooks:
    enabled: true

  service:
    enabled: false

  ingressClassResource:
    enabled: false
    controllerValue: k8s.io/ingress-nginx

  ingressClass: nginx
  watchIngressWithoutClass: true
  electionID: ingress-controller-leader-validator-default
