# Validator controller for IngressClass: nginx-internal
controller:
  image:
    repository: ingress-nginx-validator
    tag: v1.14.3-patched
    digest: ""

  admissionWebhooks:
    enabled: true

  service:
    enabled: false

  ingressClassResource:
    enabled: false
    controllerValue: k8s.io/ingress-nginx-internal

  ingressClass: nginx-internal
  watchIngressWithoutClass: false
  electionID: ingress-controller-leader-validator-internal
